pipeline {
     agent {
        docker { image 'artifactory.ap.manulife.com/docker/devops-ci-image:2.5.7' }
    }

    stages {
        stage('Step 1') {
            steps {
                echo 'This is Step 1.'
            }
            steps {
                echo 'This is Step 2.'
            }
            post {
                failure {
                    echo "Step 1 has failed!"
                }

